# spring.application.name=WhatsAppChatbotApplication
# server.port=8080
spring.application.name=WhatsAppChatbotApplication
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
server.port=${PORT:8080}